#!/bin/bash

# Firebase Configuration Commands for StepzSync Subscriptions
# Run these commands to set up your Firebase Functions environment

echo "=========================================="
echo "Firebase Subscription Configuration"
echo "=========================================="
echo ""

echo "Step 1: Set Apple App Store Shared Secret"
echo "Get this from: App Store Connect → Your App → App Information → App-Specific Shared Secret"
echo ""
echo "Run this command (replace with your actual shared secret):"
echo "firebase functions:config:set apple.shared_secret=\"YOUR_APPLE_SHARED_SECRET_HERE\""
echo ""
read -p "Press Enter to continue..."
echo ""

echo "Step 2: Set Google Play Service Account"
echo "Get this from: Google Cloud Console → IAM & Admin → Service Accounts → Create Key (JSON)"
echo ""
echo "Run this command (replace with path to your service account JSON file):"
echo "firebase functions:config:set google.play_service_account=\"\$(cat path/to/service-account.json | jq -c .)\""
echo ""
read -p "Press Enter to continue..."
echo ""

echo "Step 3: Set Android Package Name"
echo "This is your Android app package name (com.yourcompany.yourapp)"
echo ""
echo "Run this command (replace with your actual package name):"
echo "firebase functions:config:set android.package_name=\"com.stepzsync.app\""
echo ""
read -p "Press Enter to continue..."
echo ""

echo "Step 4: Verify Configuration"
echo "Run this command to check all configuration:"
echo "firebase functions:config:get"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "Step 5: Deploy Cloud Functions"
echo "Run these commands to deploy your subscription functions:"
echo "cd functions"
echo "npm install"
echo "cd .."
echo "firebase deploy --only functions"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "=========================================="
echo "Configuration Complete!"
echo "=========================================="
echo ""
echo "Next Steps:"
echo "1. Create subscription products in App Store Connect"
echo "2. Create subscription products in Google Play Console"
echo "3. Configure service accounts and API access"
echo "4. Test subscriptions in sandbox/internal testing"
echo ""
echo "For detailed instructions, see SUBSCRIPTION_SETUP_GUIDE.md"
echo ""
