// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DmimsS1ObB85DKdbJ7Wfc6eomBRISfY',
    appId: '1:1061746314202:web:your_web_app_id',
    messagingSenderId: '1061746314202',
    projectId: 'stepzsync-750f9',
    authDomain: 'stepzsync-750f9.firebaseapp.com',
    storageBucket: 'stepzsync-750f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5oi2CaD6tGdnBF4ujI_gtXXgqvcGtPE',
    appId: '1:1061746314202:android:d403cb0f9dedaa0008cee3',
    messagingSenderId: '1061746314202',
    projectId: 'stepzsync-750f9',
    storageBucket: 'stepzsync-750f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DmimsS1ObB85DKdbJ7Wfc6eomBRISfY',
    appId: '1:1061746314202:ios:e762f516999c770008cee3',
    messagingSenderId: '1061746314202',
    projectId: 'stepzsync-750f9',
    storageBucket: 'stepzsync-750f9.firebasestorage.app',
    iosBundleId: 'com.health.stepzsync.stepzsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2DmimsS1ObB85DKdbJ7Wfc6eomBRISfY',
    appId: '1:1061746314202:ios:e762f516999c770008cee3',
    messagingSenderId: '1061746314202',
    projectId: 'stepzsync-750f9',
    storageBucket: 'stepzsync-750f9.firebasestorage.app',
    iosBundleId: 'com.health.stepzsync.stepzsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2DmimsS1ObB85DKdbJ7Wfc6eomBRISfY',
    appId: '1:1061746314202:web:your_web_app_id',
    messagingSenderId: '1061746314202',
    projectId: 'stepzsync-750f9',
    authDomain: 'stepzsync-750f9.firebaseapp.com',
    storageBucket: 'stepzsync-750f9.firebasestorage.app',
  );
}